---
# if you have any prepararion task
- name: "Prepare"
  hosts: "all"
  gather_facts: true
  tasks:

    - name: "Include cryptographic content var file"
      ansible.builtin.include_vars: "../../tests/certs/main.yml"

    - name: "Include labocbz.prepare_host"
      tags:
        - "labocbz.prepare_host"
      ansible.builtin.include_role:
        name: "labocbz.prepare_host"

    - name: "Edit /etc/hosts file to add all hosts"
      loop: "{{ groups['all'] }}"
      loop_control:
        loop_var: host
      register: output
      changed_when: output.rc != 0
      when: host != ansible_host
      ansible.builtin.shell: "echo \"{{ hostvars[host]['ansible_default_ipv4']['address'] }}  {{ host }} # from Molecule\" >> /etc/hosts"

    - name: "Import cryptographic content if needed"
      run_once: yes
      loop: "{{ inv_cert_bundles }}"
      loop_control:
        loop_var: bundle
      ansible.builtin.copy:
        src: "../../tests/certs/{{ bundle.name }}.zip"
        dest: "/tmp/{{ bundle.name }}.zip"
        owner: "root"
        group: "root"
        mode: 0700

    - name: "Include labocbz.add_certificates"
      tags:
        - "labocbz.add_certificates"
      loop: "{{ inv_cert_bundles }}"
      loop_control:
        loop_var: bundle
      vars:
        add_certificates_bundle_name: "{{ bundle.name }}"
        add_certificates_bundle_type: "{{ bundle.type }}"
        add_certificates_bundle_src: "{{ bundle.src }}"
        add_certificates_bundle_dest: "{{ bundle.dest }}"
        #add_certificates_bundle_src_user: "{{ bundle.src_user }}"
        #add_certificates_bundle_src_password: "{{ bundle.src_password }}"
        #add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
        #add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
        #add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
      ansible.builtin.include_role:
        name: "labocbz.add_certificates"

    - name: "Include labocbz.install_haproxy"
      tags:
        - "labocbz.install_haproxy"
      vars:
        haproxy_path: "{{ inv_haproxy_path }}"
        haproxy_confs_path: "{{ inv_haproxy_confs_path }}"
        haproxy_error_path: "{{ inv_haproxy_error_path }}"
        haproxy_ssl_path: "{{ inv_haproxy_ssl_path }}"
        haproxy_error_files: "{{ inv_haproxy_error_files }}"
        haproxy_listen_stats: "{{ inv_haproxy_listen_stats }}"
        haproxy_listen_stats_port: "{{ inv_haproxy_listen_stats_port }}"
        haproxy_listen_stats_uri: "{{ inv_haproxy_listen_stats_uri }}"
        haproxy_stats_login: "{{ inv_haproxy_stats_login }}"
        haproxy_stats_password: "{{ inv_haproxy_stats_password }}"
        haproxy_listen_stats_pem: "{{ inv_haproxy_listen_stats_pem }}"
        haproxy_listen_stats_https: "{{ inv_haproxy_listen_stats_https }}"
      ansible.builtin.include_role:
        name: "labocbz.install_haproxy"
