---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.add_add_haproxy_http_confs_http_confs"
      tags:
        - "labocbz.add_add_haproxy_http_confs_http_confs"
      vars:
        add_haproxy_http_confs_confs_path: "{{ inv_add_haproxy_http_confs_confs_path }}"
        add_haproxy_http_confs_configurations: "{{ inv_add_haproxy_http_confs_configurations }}"
        add_haproxy_http_confs_ssl_path: "{{ inv_add_haproxy_http_confs_ssl_path }}"
      ansible.builtin.include_role:
        name: "labocbz.add_add_haproxy_http_confs_http_confs"
