---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.add_add_haproxy_http_confs__http_confs"
      tags:
        - "labocbz.add_add_haproxy_http_confs__http_confs"
      vars:
        add_haproxy_http_confs__confs_path: "{{ inv_add_haproxy_http_confs__confs_path }}"
        add_haproxy_http_confs__configurations: "{{ inv_add_haproxy_http_confs__configurations }}"
        add_haproxy_http_confs__ssl_path: "{{ inv_add_haproxy_http_confs__ssl_path }}"
      ansible.builtin.include_role:
        name: "labocbz.add_add_haproxy_http_confs__http_confs"
